### ISSUE TITLE
[Bug?] Removing a user from group

### ISSUE THREAD

**Issue by kristian-huber** [vgrem/Office365-REST-Python-Client#154] opened 2019-12-03 16:48 UTC
I am trying to remove a user from a group now that I can add them to one. I wrote the following lines of code, based on the previous post.

![image](https://user-images.githubusercontent.com/22565648/70071072-bef83e00-15c2-11ea-8675-73bd199b35e8.png)

Here is the error:

![image](https://user-images.githubusercontent.com/22565648/70071046-abe56e00-15c2-11ea-9b16-c4cd0d2ce499.png)

**Comment by kristian-huber** [comment] 2019-12-03 19:06
I implemented this code and got a 403 FORBIDDEN error like what occurred in adding a user to a group

![image](https://user-images.githubusercontent.com/22565648/70081134-f3292a00-15d5-11ea-88d7-f7c9a223c105.png)

**Comment by vgrem** [comment] 2019-12-07 12:47
Greetings!

There was a bug indeed, at least with methods:

- `UserCollection.remove_by_id`

- `UserCollection.remove_by_login_name`

Thanks for catching this!
The [latest commit](https://github.com/vgrem/Office365-REST-Python-Client/commit/ac9a0c01ec7f32b80de7cbc3d7caf031aa127301) contains a fix,  could you give it another shot?


Here is an example how to remove a user from a group:

```
target_group = client.web.site_groups.get_by_name(group_name)
target_users = target_group.users
target_users.remove_by_id(user_id)
client.execute_query()
```

**Comment by kristian-huber** [comment] 2019-12-07 21:26
When I run the code, I get this error:

![image](https://user-images.githubusercontent.com/22565648/70380774-38b76100-190e-11ea-8777-2812cd7f9e5d.png)

I don't know what is causing it. Could it be spaces in the group name?

**Comment by vgrem** [comment] 2023-09-16 18:55
Closing this one since it is considered resolved and no longer could be reproduced

**Closed by vgrem** 2023-09-16 18:55 UTC
Labels: bug, question
