### ISSUE TITLE
Not able to use it for Python 3

### ISSUE THREAD

**Issue by parthrawal** [vgrem/Office365-REST-Python-Client#31] opened 2017-07-04 10:41 UTC
Is there an issue with python 3?

**Comment by vgrem** [comment] 2017-07-04 11:37
Hello,

it should be compatible with both versions of Python: 2 and 3, but let me verify it. Will get back to you.

**Comment by parthrawal** [comment] 2017-07-04 13:25
Hi Thanks for the prompt reply.
 Below is the error i am getting
`---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-6-6b338479807a> in <module>()
      1 import json
      2 
----> 3 from office365.runtime.auth.authentication_context import AuthenticationContext
      4 from office365.runtime.client_request import ClientRequest
      5 from office365.runtime.utilities.request_options import RequestOptions

ModuleNotFoundError: No module named 'office365'`

And Yes, I have pip install the moduel :)

**Comment by vic-by** [comment] 2017-07-20 16:05
getting an error on python3.4:

_Traceback (most recent call last):
  File "auth_sharepoint_online365.py", line 2, in <module>
    from office365.runtime.auth.authentication_context import AuthenticationContext
  File "authentication_context.py", line 2, in <module>
    from office365.runtime.auth.saml_token_provider import SamlTokenProvider
  File "saml_token_provider.py", line 2, in <module>
    import urlparse
ImportError: No module named '**urlparse**'_

According to https://docs.python.org/2/library/urlparse.html:

> The urlparse module is renamed to urllib.parse in Python 3.

**Comment by parthrawal** [comment] 2017-07-22 05:12
Try this https://github.com/parthrawal/Python.O365 i have written .py file which can connect to the SharePoint Online and even has some methods to get the data from lists.

**Comment by thomasburette** [comment] 2017-07-23 15:48
@vic-by A recent commit fixes the problem : https://github.com/vgrem/Office365-REST-Python-Client/commit/90731f
Note that at this time, this commit has not yet been pushed on pypi. So if you do a `pip install Office365-REST-Python-Client` you won't get that code. Installing from git will : `pip install git+https://github.com/vgrem/Office365-REST-Python-Client.git`

**Comment by thomasburette** [comment] 2017-07-23 15:56
There is still work needed to get the library really compatible with python 3. 

I have encountered an encoding problem when running the library under python 3. It happened when doing a list.properties but I'm sure the problem is perpasive.

```
    ctx = ClientContext(url, ctx_auth)
    web = ctx.web
    ctx.load(web)
    ctx.execute_query()
    lists = web.lists
    ctx.load(lists)
    ctx.execute_query()
    lists[0].properties
```

```
 in <module>()
---> 16         lists[0].properties

c:\python\python35\lib\encodings\cp850.py in encode(self, input, final)
     17 class IncrementalEncoder(codecs.IncrementalEncoder):
     18     def encode(self, input, final=False):
---> 19         return codecs.charmap_encode(input,self.errors,encoding_map)[0]
     20
     21 class IncrementalDecoder(codecs.IncrementalDecoder):

UnicodeEncodeError: 'charmap' codec can't encode character '\u2019' in position 11052: character maps to <undefined>
```

**Comment by paulogp** [comment] 2018-01-15 11:42
I am having the same problem with Python 3: "ModuleNotFoundError: No module named 'urlparse'"
Testing the file SharePointOnline.py: Authentication Failure -> The entered and stored passwords do not match.

**Comment by parthrawal** [comment] 2018-01-15 15:02
Did you try this link https://github.com/parthrawal/Python.O365 make sure you use the service account for the same

**Comment by paulogp** [comment] 2018-01-16 11:33
Yes. Copy / Paste the code, on the bottom:
```
if __name__ == "__main__":
    UserName = "email@company.com"
    # UserName = "email@company.onmicrosoft.com"
    Password = "my_password"
    TopLevelUrl = "https://company.sharepoint.com/"
    SPOnlineHeaders(UserName, Password, TopLevelUrl)
```

The following error is returned:
```
....
IndexError: list index out of range
```

To get more detail on the error, I've inserted, on SPOnlineHeaders, the following code (print(s)):
```
response = requests.post(url, data=SharepointOnlineAuth, headers=headers)
s = str(response.content)
print(s)
```

Response:
<?xml version="1.0" encoding="utf-8" ?>...wst:FailedAuthentication...The entered and stored passwords do not match...

**Comment by parthrawal** [comment] 2018-01-16 14:43
I hope what you are using it is a service account

**Comment by paulogp** [comment] 2018-01-16 14:44
That is correct. I am using the service account.

**Comment by parthrawal** [comment] 2018-01-16 14:55
Is password correct? can you please double check it. cause i tried running the code, it's working fine. But when i entered wrong password it throws "IndexError: list index out of range" error.

**Comment by paulogp** [comment] 2018-01-17 10:38
Yes. The password is correct. This is what's happening when doing a manually login.

I write the link into the browser: https://company.sharepoint.com/

When pressing enter I am redirected to the login page: https://login.microsoftonline.com/575...71a/oauth2/authorize?client_id=...&response_mode=form_post&response_type=code%20id_token&resource=...&scope=openid&nonce=....&redirect_uri=https:%2F%2Fcompany.sharepoint.com%2F_forms%2Fdefault.aspx&wsucxt=1&client-request-id=....

After pressing the ok button at the login page I saw two fast links...
First: https://sts.company.com/adfs/ls/wia?client-request-id=...&wa=wsignin1.0&wtrealm=urn%3afederation%3aMicrosoftOnline&wctx=LoginOptions%3D3%26estsredirect%3d2%26estsrequest%....&cbcxt=&username=myemail%company.com&mkt=&lc=
... And ...
Second: https://login.microsoftonline.com/login.srf?client-request-id=...

And finally stops at the required page:
https://company.sharepoint.com/

**Comment by rajeevteejwal** [comment] 2018-10-11 20:45
I run this code found that it is throwing 403 error somewhere in code.

response = requests.post(url,data=SharepointOnlineAuth,headers=headers)
s = str(response.content)
print(s)
"b'403 FORBIDDEN'"

**Comment by rajeevteejwal** [comment] 2018-10-11 20:57
I forgot to use endpoint

url="https://login.microsoftonline.com/extSTS.srf"

**Comment by viogp** [comment] 2018-10-17 17:15
> urlpar

I'm having the same problem with urlparse (Python 3.6.5 :: Anaconda, Inc.). This was solved by modifying saml_token_provider.py: `from urllib.parse import urlparse [...] url = urlparse(self.url)`

Then I was missing web, which I installed it with: `pip install lpthw.web`. However, there seems to be an issue, as now I'm getting the following problem:
` from web import Web
  File "C:\ProgramData\Anaconda3\lib\site-packages\web\__init__.py", line 14, in <module>
    import utils, db, net, wsgi, http, webapi, httpserver, debugerror
ModuleNotFoundError: No module named 'utils'
`

**Comment by viogp** [comment] 2018-10-17 17:28
> 
> 
> Install the utils module in anaconda.

Thanks. After installing utils, I also needed to install db...it might be useful to have a requirements.txt check in the package? 

What is happening now is that the print statements are not adequate for python3:
`
print "var", var
              ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("var", var)?
`

**Comment by Dan-S** [comment] 2018-11-05 03:36
@viogp Thanks for posting your progress here, would be good if we can iron some of these kinks out.  Currently are using this library in py 2.7 and would like to these workflows over to py 3.

**Comment by jpzapata99** [comment] 2019-08-08 18:57
Hi. I have a problem using this library. 
An error occurred while retrieving token: AADSTS90023: Invalid STS request.
An error occurred while retrieving auth cookies
return 'FedAuth=' + self.FedAuth + '; rtFa=' + self.rtFa
TypeError: can only concatenate str (not "NoneType") to str
Any can help me?

**Comment by vgrem** [comment] 2020-05-16 16:29
Since the library is officially compatible with both Python 2  and Python 3 runtimes, propose to close this issue.

**Closed by vgrem** 2020-05-16 16:29 UTC
Labels: bug, enhancement

**Comment by pThonprogrammer** [comment] 2020-07-01 21:14
hi,

I am getting this error "ModuleNotFoundError: No module named 'office365.sharepoint.client_context'" when I use project environment in pycharm during running. BUT it will work just fine if i use Python system environment. The same behavior either I use Python 3.6 or 3.7.

Please help!
Thanks.

**Comment by vincentsahl-capgemini** [comment] 2022-07-25 09:33
> There is still work needed to get the library really with python 3.
> 
> I have encountered an encoding problem when running the library under python 3. It happened when doing a list.properties but I'm sure the problem is perpasive.
> 
> ```
>     ctx = ClientContext(url, ctx_auth)
>     web = ctx.web
>     ctx.load(web)
>     ctx.execute_query()
>     lists = web.lists
>     ctx.load(lists)
>     ctx.execute_query()
>     lists[0].properties
> ```
> 
> ```
>  in <module>()
> ---> 16         lists[0].properties
> 
> c:\python\python35\lib\encodings\cp850.py in encode(self, input, final)
>      17 class IncrementalEncoder(codecs.IncrementalEncoder):
>      18     def encode(self, input, final=False):
> ---> 19         return codecs.charmap_encode(input,self.errors,encoding_map)[0]
>      20
>      21 class IncrementalDecoder(codecs.IncrementalDecoder):
> 
> UnicodeEncodeError: 'charmap' codec can't encode character '\u2019' in position 11052: character maps to <undefined>
> ```

I have the same issue. Did you found a way to solve it?
