### ISSUE TITLE
KeyError: 'd' - payload = payload['d']['GetContextWebInformation']

### ISSUE THREAD

**Issue by Rich107** [vgrem/Office365-REST-Python-Client#244] opened 2020-08-03 17:36 UTC
Hi All, 

I was previously using version 2.1.3. This worked until the end of last month when it started to get an access_token KeyError, stack trace below:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/code/carbon_service/tasks.py", line 9, in update

)
  File "/code/carbon_service/services/Update.py", line 117, in update
    upload_file(context=ctx, doc_library='XXX', pdf_file=f, metadata=metadata)
  File "/code/carbon_service/services/Update.py", line 48, in upload_file
    file = upload_file_into_library(library, metadata.pop('Name'), file_content, metadata=metadata)
  File "/code/carbon_service/services/Update.py", line 35, in upload_file_into_library
    context.execute_query()
  File "/usr/local/lib/python3.7/site-packages/office365/runtime/client_runtime_context.py", line 38, in execute_query
    self.pending_request.execute_query()
  File "/usr/local/lib/python3.7/site-packages/office365/runtime/client_request.py", line 32, in execute_query
    return self.execute_pending_queries()
  File "/usr/local/lib/python3.7/site-packages/office365/runtime/client_request.py", line 38, in execute_pending_queries
    response = self.execute_request_direct(request)
  File "/usr/local/lib/python3.7/site-packages/office365/runtime/client_request.py", line 105, in execute_request_direct
    self.context.authenticate_request(request_options)
  File "/usr/local/lib/python3.7/site-packages/office365/runtime/client_runtime_context.py", line 16, in authenticate_request
    self.__auth_context.authenticate_request(request)
  File "/usr/local/lib/python3.7/site-packages/office365/runtime/auth/authentication_context.py", line 37, in authenticate_request
    request_options.set_header('Authorization', self.provider.get_authorization_header())
  File "/usr/local/lib/python3.7/site-packages/office365/runtime/auth/acs_token_provider.py", line 76, in get_authorization_header
    return 'Bearer {0}'.format(self.access_token["access_token"])
KeyError: 'access_token'
```

I've tried creating a newly registered app in SharePoint without any luck. (It stopped working exactly 12 months after I set it up making me think it was a permissions expiry problem.)

Next, I tried updating to the latest version (2.1.7.post1) on pypi which just gives me new errors but I think I am past the permissions problem?

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/code/carbon_service/services/Update.py", line 118, in update
    upload_file(context=ctx, doc_library='XXX', pdf_file=f, metadata=metadata)
  File "/code/carbon_service/services/Update.py", line 49, in upload_file
    file = upload_file_into_library(library, metadata.pop('Name'), file_content, metadata=metadata)
  File "/code/carbon_service/services/Update.py", line 36, in upload_file_into_library
    context.execute_query()
  File "/usr/local/lib/python3.7/site-packages/office365/sharepoint/client_context.py", line 43, in execute_query
    super(ClientContext, self).execute_query()
  File "/usr/local/lib/python3.7/site-packages/office365/runtime/client_runtime_context.py", line 37, in execute_query
    self.pending_request.execute_query()
  File "/usr/local/lib/python3.7/site-packages/office365/runtime/client_request.py", line 30, in execute_query
    for request in self.build_request():
  File "/usr/local/lib/python3.7/site-packages/office365/runtime/odata/odata_request.py", line 35, in build_request
    self._events['before'](request, qry)
  File "/usr/local/lib/python3.7/site-packages/office365/sharepoint/client_context.py", line 47, in _build_specific_query
    self.ensure_form_digest(request)
  File "/usr/local/lib/python3.7/site-packages/office365/sharepoint/client_context.py", line 26, in ensure_form_digest
    self.request_form_digest()
  File "/usr/local/lib/python3.7/site-packages/office365/sharepoint/client_context.py", line 37, in request_form_digest
    payload = payload['d']['GetContextWebInformation']
KeyError: 'd'
```

Any and all help would be appreciated! Kudos to @vgrem who helped me just over 12 months ago today!

Code thats failing: 
```
def upload_file_into_library(target_library, name, content, metadata):
    target_library.context.json_format.metadata = 'verbose'
    context = target_library.context
    info = FileCreationInformation()
    info.content = content
    info.url = name
    info.overwrite = True
    target_file = target_library.files.add(info)
    context.execute_query()
    item = target_file.listitem_allfields
    for k, v in metadata.items():
        item.set_property(name=k, value=v)
    item.update()
    context.execute_query()
    return target_file
```

**Comment by Rich107** [comment] 2020-08-11 11:49
Hi @vgrem 

No doubt you're short for time. Any pointers you could give on this, so I can look in the right direction?

Kind Regards
Richard

**Comment by vgrem** [comment] 2020-08-11 13:11
Greetings Richard,

regarding 

> I've tried creating a newly registered app in SharePoint without any luck. (It stopped working exactly 12 months after I set it up making me think it was a permissions expiry problem.)

indeed, it appears to be the case here and [this article ](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in) explains how to replace an expiring client secret.


Out of curiosity (and since `2.1.7.post1` is outdated and a few authenticated issues have been resolved since then), could you  please give another shot but with the _latest version_ of library instead?

Since the latest version is [not available yet yet from official package](https://github.com/vgrem/Office365-REST-Python-Client/issues/75), it could be downloaded from GitHub meanwhile: 

pip install git+https://github.com/vgrem/Office365-REST-Python-Client.git

or from [alternative index](https://pypi.org/project/office365-rest-client/):

**Comment by Rich107** [comment] 2020-08-14 14:30
Thanks @vgrem 

Your comments above were a great help. For anyone and the script is working again now for everyone else's benefit who might come across this. We had to do the following:

-  Upgrade to the GitHub version as vgrem suggested

- Reset our credentials using these docs: `https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azureacs`
- and finally, change a couple of API calls which must have been renamed during the upgrades between versions:

This:
`from office365.sharepoint.file_creation_information import FileCreationInformation`
Changed to this:
`from office365.sharepoint.files.file_creation_information import FileCreationInformation`

This:
```
    target_file = target_library.root_folder.files.add(info)
    context.execute_query()
    item = target_file.listitem_allfields
```
changed to:
```
    target_file = target_library.rootFolder.files.add(info)
    context.execute_query()
    item = target_file.listItemAllFields
```

All the best
Rich

**Comment by vgrem** [comment] 2020-09-04 09:56
Closing this one since has been confirmed as resolved.

**Closed by vgrem** 2020-09-04 09:56 UTC
Labels: question

**Comment by dankrzeminski32** [comment] 2021-07-22 21:10
Excuse me but I am in a difficult situation attempting to write managed metadata to a column in our sharepoint doc library. In your function what object is "target_library" referencing?
