### ISSUE TITLE
Error download file from sharepoint

### ISSUE THREAD

**Issue by cestes** [vgrem/Office365-REST-Python-Client#671] opened 2023-04-13 18:51 UTC
Hi,

I'm getting the following when attempting to download from sharepoint:

`office365.runtime.client_request_exception.ClientRequestException: ('-2147024891, System.UnauthorizedAccessException', 'Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))', "403 Client Error: Forbidden for url: https://myorg.sharepoint.com/_api/Web/getFileByServerRelativeUrl('%2Fsites%2Fmyteam%2FShared%20Documents%2FGeneral%2Fbk.jpg')?$select=ServerRelativePath")`

I'm copying directly from the example.  My code looks like this:

```
from office365.runtime.auth.client_credential import ClientCredential
from office365.sharepoint.client_context import ClientContext
from office365.sharepoint.files.file import File

site_url = "https://myorg.sharepoint.com"
file_url = "/sites/myteam/Shared Documents/General/bk.jpg"

client_id = "abc"
client_secret = "123"

client_credentials = ClientCredential(client_id,client_secret)
ctx = ClientContext(site_url).with_credentials(client_credentials)

with open('bk.jpg', "wb") as local_file:
     file = ctx.web.get_file_by_server_relative_url(file_url).download(local_file).execute_query()
```

Is this a code issue or do I need to do something on O365 to allow the get file by relative url?

**Comment by dkuska** [comment] 2023-04-14 12:29
Sounds like a permission issue, code looks fine to me. Did you follow these [guidelines](https://learn.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azureacs) to grant the required access to the Service Principal/Managed Identity/Business Application?

**Comment by vgrem** [comment] 2023-10-20 08:42
Greetings, 

according to your example client get initialized against root site collection: 

`site_url = "https://myorg.sharepoint.com"
`
while file is retrieved from another site collection `/sites/myteam`:

`file_url = "/sites/myteam/Shared Documents/`

which is not supposed by design since site collection in SharePoint represent an isolated security container.

One solution would be to change site url to target a valid site collection:

`site_url = "https://myorg.sharepoint.com/sites/myteam"`

then file could be addressed by server relative url or site relative url:

`file_url = "Shared Documents/`

**Closed** 2023-10-20 08:52 UTC
Labels: question
