### ISSUE TITLE
Not able to download files from SharePoint document  Library 

### ISSUE THREAD

**Issue by rangannanaik** [vgrem/Office365-REST-Python-Client#449] opened 2021-12-21 08:39 UTC
Hi Team,

I am downloading the  files from SharePoint  document  library but few files name contains # character that  time i am getting  error "404 Client Error: Not Found for url:" but file exist in SharePoint 

Kindly  help  on this .

Regards,
Ranganna Naik

**Comment by vgrem** [comment] 2022-01-23 15:14
Hey,

there are certain shortcomings with SharePoint API itself when files and folders are addressed by server relative url and it affects several methods in library e.g. `Web.get_file_by_server_relative_url` method.    

The root cause why special symbols (namely `#`) is summarized in [Supporting % and # in files and folders with the ResourcePath API](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/supporting-and-in-file-and-folder-with-the-resourcepath-api):

> Support for % and # in files and folders is being deployed within SharePoint Online. Unfortunately, due to existing API structures and calling patterns, working with these file names can sometimes become ambiguous.

**Resolution**
When addressing files, prefer `Web.get_file_by_server_relative_path(path)` over `Web.get_file_by_server_relative_url(url)` method, same goes to another resources (e.g. Folders).

Similar thread:  #316

**Closed by vgrem** 2022-01-23 15:14 UTC
Labels: question
