### ISSUE TITLE
How to copy files within SharePoint?

### ISSUE THREAD

**Issue by AniPetr** [vgrem/Office365-REST-Python-Client#360] opened 2021-06-03 10:22 UTC
Hi, 
I want to recursively copy all files and folders in SharePoint into a new folder. 
For the start, I have tried the following code:
```

url = 'https://MyCompany.sharepoint.com/sites/MyTeam'
source_folder_url = '/sites/MyTeam/Shared Documents/from'
target_folder_url = '/sites/MyTeam/Shared Documents/to'
ctx = ClientContext(url).with_credentials(ClientCredential(client_id, client_secret))

source_folder = ctx.web.get_folder_by_server_relative_url (source_folder_url)
target_folder = source_folder.copy_to (target_folder_url).get().execute_query()

files = target_folder.files
ctx.load(files).execute_query()    
for f in files:
    print(f.properties["ServerRelativeUrl"])
```
Nothing happens with this code and nothing is printed.
Then I tried to copy files with this piece of code:
```
files = source_folder.files
ctx.load(files).execute_query()  
for f in files:
    f.copyto(target_folder_url, 0 )
    ctx.execute_query()
```
I also tried `File.copyto_using_path(target_folder_url, 0)`, because I was not sure about the differences between these 2 functions. And just to try, I have checked 
`File.moveto()` function, too. All these 3 functions give me 400 Client Error.

Please help me to understand what are my mistakes here.

**Comment by vgrem** [comment] 2021-07-08 08:26
Hi,

thank you for reporting, indeed it confirmed to be a bug and could be reproduced when folder resides in non root site collection .

Regarding the difference between `File.copy_to` and `File.copy_to_using_path` methods, it could be summarized to support `%` and `#` characters when addressing File/Folder resources by path , thats the reason  `File.copy_to_using_path` should be preffered over  `File.copy_to`. Refer [this article](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/supporting-and-in-file-and-folder-with-the-resourcepath-api) for a more details.

Closing this one as a resolved, the fix is available in [`2.3.5` version](https://github.com/vgrem/Office365-REST-Python-Client/tree/2.3.5).

**Closed by vgrem** 2021-07-08 08:26 UTC
Labels: bug
