### ISSUE TITLE
search query add_query missing

### ISSUE THREAD

**Issue by emre1e** [vgrem/Office365-REST-Python-Client#601] opened 2022-11-22 11:25 UTC
Hello together,

the function add_query could not be resolved by Office365/sharepoint/search/service.py

I think any reference is missing. 

Can you check it please? 

Exception has occurred: AttributeError
'function' object has no attribute 'add_query'

**Comment by vgrem** [comment] 2023-09-18 20:33
Closing this one since no longer could be reproduced

**Closed by vgrem** 2023-09-18 20:33 UTC
Labels: question
