### ISSUE TITLE
Not able to get a view for a list

### ISSUE THREAD

**Issue by florinmihut** [vgrem/office365-rest-python-client#190] opened 2020-05-11 20:50 UTC
How to reproduce:

```
        list_obj = ctx.web.lists.get_by_title(self.conf["sharepoint_folder"])
        views = list_obj.views
        self.ctx.load(views)
        self.ctx.execute_query()
        view = views.get_by_title("MyFancyView")

```
At the last line I get:
```
    view = views.get_by_title("MyFancyView")
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\office365\sharepoint\view_collection.py", line 14, in get_by_title
    ResourcePathServiceOperation(self.context, self.resourcePath, "GetByTitle", [view_title]))
TypeError: __init__() takes from 2 to 4 positional arguments but 5 were given
```

**Comment by vgrem** [comment] 2020-05-11 21:41
Greetings,

in what version do you experience this error, cant reproduce it in the latest version. The latest version could be installed from GitHub:

`pip install git+https://github.com/vgrem/Office365-REST-Python-Client.git `

**Comment by florinmihut** [comment] 2020-05-11 23:01
I am using the version from pip 2.1.7. 

The error seems to be in viewcollection.py
where ResourcePathServiceOperation is created (for GetByTitle):
ResourcePathServiceOperation(self.context, self.resourcePath, "GetByTitle", [view_title]))
should be:
ResourcePathServiceOperation("GetByTitle", [view_title], self.resourcePath) 

With this, I can get the view but I am not sure how I can get its contents. I would have expected to have a get_items (or equivalent) with CamlQuery argument. 
Is this not yet implemented?

**Comment by florinmihut** [comment] 2020-05-12 08:16
How to get the contents of a query is explained in #65.
On the other hand, I am not getting the fields that I was expecting. I get the same fields as I get normally.
I tried to make the view as default for the list but still no change, I see the same fields in the properties.

The code I am using is:
```
        view = list_obj.views.get_by_title("ReMakerView")
        ctx.load(view, "ViewQuery")
        ctx.execute_query()

        # 2.get items for View query
        qry = CamlQuery()
        # I am even trying setting the entire ViewXml Caml query but I haven't seen any effect
        qry.ViewXml = view.properties["ListViewXml"]
        items = list_obj.get_items(qry)
        ctx.load(items)
        ctx.execute_query()
```
I can see that the ViewXML contains something valid:
```
'<View Name="{E884CB01-D667-4924-88C9-DC8D29640871}" DefaultView="TRUE" MobileView="TRUE" MobileDefaultView="TRUE" Type="HTML" Scope="Recursive" DisplayName="ReMakerView" Url="/sites/Site/Library/Forms/ReMakerView.aspx" Level="1" BaseViewID="1" ContentTypeID="0x" ImageUrl="/_layouts/15/images/dlicon.png?rev=47" >
	<Query>
		<GroupBy Collapse="TRUE" GroupLimit="30">
			<FieldRef Name="Program" />
			<FieldRef Name="Document_x0020_Type" />
		</GroupBy>
		<OrderBy>
			<FieldRef Name="Program" />
			<FieldRef Name="FileLeafRef" />
		</OrderBy>
	</Query>
	<ViewFields>
		<FieldRef Name="DocIcon" />
		<FieldRef Name="LinkFilename" />
		<FieldRef Name="Modified" />
		<FieldRef Name="Editor" />
		<FieldRef Name="Program" />
		<FieldRef Name="Document_x0020_Type" />
		<FieldRef Name="Document_x0020_Status" />
		<FieldRef Name="Document_x0020_Maturity_x0020_Level" />
		<FieldRef Name="ID" />
		<FieldRef Name="Created" />
		<FieldRef Name="Author" />
		<FieldRef Name="FileSizeDisplay" />
		<FieldRef Name="_CheckinComment" />
	</ViewFields>
	<RowLimit Paged="TRUE">30</RowLimit>
	<Aggregations Value="Off" />
	<JSLink>clienttemplates.js</JSLink>
	<XslLink Default="TRUE">main.xsl</XslLink>
	<ViewData />
	<Toolbar Type="Standard"/>
</View>'
```
But it seems that providing this when getting the elements does not make any difference. 
Any idea what could be wrong?

**Comment by vgrem** [comment] 2020-05-12 21:51
#65 indeed, is a way to go when it comes to retrieving list items per list view.

Now comes the turn of [`View.ListViewXml`  property](https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-server/jj171908(v=office.15)),  it represents _schema_ for View and has nothing todo with CAML query which `List.get_items` method expects (and the reason why the query is getting ignored)


Another option to retrieve list items per view would be to utilize the latest version 

```
view_items = target_list.views.get_by_title(view_title).get_items()
client.load(view_items)
client.execute_query()

```

**Comment by florinmihut** [comment] 2020-05-14 08:31
Thanks Vadim, but still no success.
I upgraded to the latest version.

What I am trying is to get the damn filename (among some other things but this is the most important part) in the fields that are returned by the list view (by default I get only the metadata). 
I thought that if I create a view of the list in SharePoint I will see/get the same content with the python client. 
I am assuming that whatever view assigned by default is for a list that would be used to return the fields.

Of course, I can (for each item from the view_items)  request the file property. This takes some time and generates some traffic if I need to get that for each and every item.
It must work because I would assume that web content is generated in the same way, but there must be something I am missing. 

`
        list_obj = self.ctx.web.lists.get_by_title(self.conf["sharepoint_folder"])
        items = list_obj.views.get_by_title("MyAwesomeView").get_items()
        self.ctx.load(items)
        self.ctx.execute_query()

        for item in items:
            file = item.file
            self.ctx.load(file)
            self.ctx.execute_query()
            row = self.get_properties(file) # this is a function that ignores __deferred properties
            meta_row = self.get_properties(item)
            row.update(meta_row)
            rows.append(row)
        return rows
`
This is ugly. Is there another way to specify which fields I want in my retuned get_items() response?

**Comment by florinmihut** [comment] 2020-05-14 09:37
Is something like this possible?

```
https://my.sharepoint.com/sites/Site/_api/web/lists/
getbytitle('MyAwesomeList')/items?
$select=
	FieldValuesAsText/FileRef,
	Title,
	Program,
	Document_x0020_Type,
	Document_x0020_Status,
	Document_x0020_Maturity_x0020_Level
&$expand=FieldValuesAsText
```

**Comment by florinmihut** [comment] 2020-05-14 16:48
[Documentation link](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests#select-items-to-return)
Solved the problem but not with a view but with query options:

```
        list = self.ctx.web.lists.get_by_title("MyListTitle")
        items = list.get_items()
       # one can read in the link above about select and other options
       # documentation is very bad what are the predefined fields that can be requested
       # one can define new columns in share point and other fields that can be requested here
        items.queryOptions.select = ["ID", "UniqueId", "FileRef", "LinkFilename", "Title"]
        self.ctx.load(items)
        self.ctx.execute_query()
```
@vgrem Thank you for your help! From my point of view this issue can be closed but to make sure this is not forgoten, I had to do 
`pip install --upgrade git+https://github.com/vgrem/Office365-REST-Python-Client.git@e7e9ef645fb972e5e0a4990bf124acaf0ce1a181`
to make it work, with the latest version one will get the error above.

**Comment by vgrem** [comment] 2020-05-15 19:32
Good to know!

Propose to close it as resolved.

**Closed by vgrem** 2020-05-15 19:32 UTC
Labels: question, sharepoint
