### ISSUE TITLE
Release latest version to pypi?

### ISSUE THREAD

**Issue by minsis** [vgrem/Office365-REST-Python-Client#225] opened 2020-07-15 15:03 UTC
The version of this library I need isn't released to pypi. Are there plans to release the newer version of it?

**Comment by vgrem** [comment] 2020-07-15 18:56
Greetings! 

Affirmative, the plans to release as soon as we have a chance. Hoping to hear from the @kgadek soon, who kindly maintains this project.
 
For now, the _latest_ version could be installed from [alternative index URL](https://pypi.org/project/office365-rest-client/)

**Comment by vgrem** [comment] 2020-07-15 18:56
Closing this one as a duplicate of #75

**Closed by vgrem** 2020-07-15 18:56 UTC
Labels: question
